kotlin.stdlib.default.dependency=false
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true

# Auto-download du JDK 21 si nécessaire (toolchain)
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true

# Si tu veux forcer un chemin JDK 21 spécifique (décommente UNE ligne):
# org.gradle.java.home=/home/TON_USER/.sdkman/candidates/java/21.0.5-tem
# org.gradle.java.home=/opt/homebrew/opt/openjdk@21
# org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
# org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.5.11-hotspot
